[package]
name = "agc-physics"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
agc-utils = { path = "../utils"}
arrayvec = "0.7.6"
fixedstr = "0.5.10"

[lib]
name = "agc_physics"
path = "src/lib.rs"

